<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Hestia.Exception\Hestia.Exception.csproj" />
    <ProjectReference Include="..\Hestia.Application\Hestia.Application.csproj" />
    <ProjectReference Include="..\Hestia.Infrastructure\Hestia.Infrastructure.csproj" />
  </ItemGroup>

</Project>
